### PR TITLE
Django 2.1 upgrade

### PR DESCRIPTION
**Pull request by fabiopintodacosta**
Upgrading to the new Django version raised some Exceptions on these lines. These were the fixes I implemented in my local version.

more info: https://docs.djangoproject.com/en/2.1/releases/2.1/#what-s-new-in-django-2-1

### CODE REVIEW

**Comment by etianen** [comment]
Thanks for looking into this?

What was the problem caused by not including "has_view_permission" in the template render?

**Comment by fabiopintodacosta** [comment]
No worries.

At the /adminauth/user/invite/ form (GET), I'd get a KeyError exception for 'has_view_permission' (at the invite_user function). So, I followed the clue and tried initialising it too, for which it threw another different one (that time for the 'has_editable_inline_admin_formsets' key).

**Comment by etianen** [comment]
I'll have a new release out once the tests have run against Django 2.1

**Comment by fabiopintodacosta** [comment]
Alright, thank you very much :)

(You're probably aware, but Django 2.1.1 has already been launched, fwiw)

**Comment by etianen** [comment]
Looks like the password_reset view is currently breaking Django 2.1 integration.

I don't have the time to debug this myself. If you can submit a pull request that makes all the Travis CI tests pass, I'll happily pull it in and push out a new release.

https://travis-ci.org/etianen/django-usertools/jobs/422989549

**Comment by fabiopintodacosta** [comment]
Seemed to have to do with Django deprecating function based auth views. Sorry, should've seen that myself. Check pull request 5, all tests are passing. Thanks

**Pull request merged**
